### ISSUE TITLE
bug: fix Classroom SDK to address Scale and Scale Value verbiage issues

### ISSUE THREAD

**Issue by kpalania** [snowpal/pitch-classroom-sdk#11]

**Comment by kpalania** [comment]
@AnishKhatri Is this done? Can you add PR link?

**Comment by AnishKhatri** [comment]
### PR: https://github.com/snowpal/pitch-classroom-sdk/pull/13

**Comment by kpalania** [comment]
@AnishKhatri Merged but `did not review`. Let's discuss the changes.
